name: Linux Build Status
on:
  [push, pull_request]
jobs:
  build-test:
    runs-on: ubuntu-latest
    if: "!contains(github.ref, 'coverity_scan')"
    strategy:
      matrix:
        DOCKER_IMAGE: ["ubuntu-18.04", "ubuntu-20.04", "fedora-32", "opensuse-leap"]
        TPM2TSS_BRANCH: ["3.0.x"]
        TPM2TOOLS_BRANCH: ["4.0"]
        CC: ["gcc", "clang"]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Launch Container
        env:
          DOCKER_IMAGE: "${{ matrix.DOCKER_IMAGE }}"
          TPM2TSS_BRANCH: "${{ matrix.TPM2TSS_BRANCH }}"
          TPM2TOOLS_BRANCH: "${{ matrix.TPM2TOOLS_BRANCH }}"
          CC: "${{ matrix.CC }}"
        run: ./.ci/ci-runner.sh
      - name: failure
        if: ${{ failure() }}
        run: cat build/test-suite.log || true
